param([string]$Destination=".\\vivek-v-rao-full",[switch]$Mirror)
$ErrorActionPreference="Continue"
New-Item -ItemType Directory -Force -Path $Destination | Out-Null
$repos=@(
  "High-Frequency-Trading-Software"
  "OHLC-Vol"
  "Conditional-Skew"
  "Yahoo-Option-Prices"
  "YahooFundamentals"
  "Delta-Gamma"
  "ReturnDistributions"
  "Earnings-Dates"
  "YahooFinance"
  "yfinance-corporate-actions-prices"
  "Intraday-Vol"
  "intraday-prices"
  "Root-Mean-Square-Bias"
  "ProbabilityDistributions"
  "Non-lognormal-option-pricing"
  "FinanceBooks"
  "Paths"
  "BinomialTree"
  "Option-Portfolio"
  "vix_utils"
  "ReturnStats"
  "GetPriceData"
  "Conditional-Return-Stats"
  "moving-average-systems"
  "implied-vol-speed"
  "OHLC-Correlation"
  "Sharpe-out-of-sample"
  "Return-Mixtures"
  "Implied-Vol-Surface"
  "Time-Series-Distributions"
  "cpp-dataframe"
  "Student-t-option-pricing"
  "Return-Mixtures-of-Normals"
  "GARCH"
  "Returns-Azzalini-Skew-t"
  "Beta"
  "ETF-Risk-Lab"
  "Bivariate-Student-t-distribution"
  "DeltaHedging"
  "Daily-Range-by-President"
  "NonNormalOptionLab"
  "Return-Distributions-R"
  "Miscellaneous"
  "Delta-Hedging-with-Bands"
  "GARCH-SV-ACF"
  "GARCH-from-scratch"
  "GARCH-variants"
  "Weighted-Historical-Volatility"
  "Fit-Distributions"
  "Constrained-Autoregression"
  "GARCH-in-mean"
  "GARCH-models"
  "PosReg"
  "GARCH-R"
  "Windows-File-Utils"
  "vix_futures_strategies"
  "Returns-Skew-t"
)
foreach($repo in $repos){
  $url="https://github.com/vivek-v-rao/$repo.git"
  Write-Host "=== $repo ==="
  if($Mirror){
    $target=Join-Path $Destination "$repo.git"
    if(Test-Path $target){git -C $target remote update --prune}else{git clone --mirror $url $target}
  }else{
    $target=Join-Path $Destination $repo
    if(Test-Path (Join-Path $target ".git")){git -C $target fetch --all --tags --prune; git -C $target pull --ff-only}else{git clone $url $target}
  }
}
Write-Host "Done: $Destination"
